import { getCurrentWindow } from '@tauri-apps/api/window'
import { useEffect, useRef, useState } from 'react'
import { generationCancel, generationGetReadiness, generationGetRun, generationStart } from './api/generation'
import { documentCreate, documentDelete, documentGet, documentGetProperties, documentLinkArtifact, documentLinkPaper, documentList, documentUnlinkArtifact, documentUnlinkPaper, documentUpdate, type DocumentListItem, type DocumentProperties } from './api/documents'
import { getPaper, importArxivPaper, listPapers, type PaperDetail, type PaperListItem } from './api/papers'
import { studyDeleteArtifact, studyGet, studyListArtifacts, studySaveArtifact, type StudyArtifact, type StudyView } from './api/study'
import { signalRuntimeSmokeReady, systemGetInfo, type SystemInfo } from './api/system'
import { DocumentWorkspace, type DocumentWorkspaceHandle } from './features/editor/NoteWorkspace'
import { ImportPaperDialog } from './features/import/ImportPaperDialog'
import { StudyGenerationDialog } from './features/transform/TransformDialog'
import type { Activity, OpenTab, WorkspaceApis } from './features/workspace/types'
import { Icon } from './ui/Icon'
import paprvLogo from './assets/paprv-logo.png'

const defaults: WorkspaceApis = { papers:{ listPapers, getPaper, importArxivPaper }, documents:{ list:documentList, get:documentGet, create:documentCreate, update:documentUpdate, delete:documentDelete, getProperties:documentGetProperties, linkPaper:documentLinkPaper, unlinkPaper:documentUnlinkPaper, linkArtifact:documentLinkArtifact, unlinkArtifact:documentUnlinkArtifact }, study:{ get:studyGet, listArtifacts:studyListArtifacts, saveArtifact:studySaveArtifact, deleteArtifact:studyDeleteArtifact }, generation:{ getReadiness:generationGetReadiness, start:generationStart, getRun:generationGetRun, cancel:generationCancel } }
type Theme = 'dark'|'light'; type Layout = 'wide'|'intermediate'|'compact'; type Startup = {status:'loading'}|{status:'ready';info:SystemInfo}|{status:'error'}
const currentLayout=():Layout=>window.innerWidth<=799?'compact':window.innerWidth<=1023?'intermediate':'wide'
function storedTheme(): Theme { try { const value=localStorage.getItem('paprv.theme'); return value==='light'?'light':'dark' } catch { return 'dark' } }
function StartupBoundary({children}:{children:React.ReactNode}) { const [state,setState]=useState<Startup>({status:'loading'}); const [attempt,setAttempt]=useState(0); useEffect(()=>{ let active=true; delete document.documentElement.dataset.paprvReady; void systemGetInfo().then(info=>{if(active)setState({status:'ready',info})},()=>{if(active)setState({status:'error'})}); return()=>{active=false;delete document.documentElement.dataset.paprvReady} },[attempt]); useEffect(()=>{if(state.status!=='ready')return; document.documentElement.dataset.paprvReady='true';document.documentElement.dataset.paprvPlatform=state.info.platform;document.documentElement.dataset.paprvVersion=state.info.version;void signalRuntimeSmokeReady(state.info).catch(()=>undefined)},[state]); if(state.status==='loading')return <main className="startup-state"><span className="startup-mark"><img src={paprvLogo} alt=""/>Paprv</span><span>Opening your paper workspace…</span></main>; if(state.status==='error')return <main className="startup-state startup-error"><div role="alert"><h1>Paprv could not start</h1><p>Reconnect to the desktop runtime, then try again.</p><button onClick={()=>setAttempt(v=>v+1)}>Try again</button></div></main>; return <>{children}<output hidden data-paprv-runtime-ready="true">PAPRV_RENDERER_READY:{state.info.platform}:{state.info.version}</output></> }

function Workspace({apis}:{apis:WorkspaceApis}) {
  const [activity,setActivity]=useState<Activity>('library'); const [layout,setLayout]=useState<Layout>(currentLayout); const [drawer,setDrawer]=useState<'explorer'|'inspector'|null>(null); const [papers,setPapers]=useState<PaperListItem[]>([]); const [documents,setDocuments]=useState<DocumentListItem[]>([]); const [query,setQuery]=useState(''); const [paperRovingId,setPaperRovingId]=useState<string|null>(null); const [documentRovingId,setDocumentRovingId]=useState<string|null>(null); const [tabs,setTabs]=useState<OpenTab[]>([]); const [activeKey,setActiveKey]=useState<string|null>(null); const [capturedSelection,setCapturedSelection]=useState<{documentId:string;revision:number;startUtf8:number;endUtf8:number}|null>(null); const [paperDetails,setPaperDetails]=useState<Record<string,PaperDetail>>({}); const [studyViews,setStudyViews]=useState<Record<string,StudyView>>({}); const [artifacts,setArtifacts]=useState<Record<string,StudyArtifact[]>>({}); const [properties,setProperties]=useState<DocumentProperties>({documentId:'',papers:[],artifacts:[]}); const [generationOpen,setGenerationOpen]=useState(false); const [importOpen,setImportOpen]=useState(false); const [deleteDocumentId,setDeleteDocumentId]=useState<string|null>(null); const [deletePending,setDeletePending]=useState(false); const [deleteError,setDeleteError]=useState(''); const [theme,setTheme]=useState<Theme>(storedTheme); const [announcement,setAnnouncement]=useState(''); const [linkPaperId,setLinkPaperId]=useState(''); const [linkDocumentId,setLinkDocumentId]=useState('')
  const docsRef=useRef<DocumentWorkspaceHandle>(null); const quickRef=useRef<HTMLInputElement>(null); const explorerRef=useRef<HTMLElement>(null); const inspectorRef=useRef<HTMLElement>(null); const drawerReturnRef=useRef<HTMLButtonElement|null>(null); const deleteDialogRef=useRef<HTMLDivElement>(null); const deleteReturnRef=useRef<HTMLButtonElement|null>(null); const deletePendingRef=useRef(false); const closePendingRef=useRef(false); const generationReturnRef=useRef<HTMLElement|null>(null); const importReturnRef=useRef<HTMLButtonElement|null>(null); const activeDocumentIdRef=useRef<string|null>(null); const openIntentRef=useRef(0)
  const activeTab=tabs.find(t=>t.key===activeKey)??null; const activeDocumentId=activeTab?.kind==='document'?activeTab.documentId:null; activeDocumentIdRef.current=activeDocumentId; const activePaper=activeTab?.kind==='study'?paperDetails[activeTab.paperId]??null:null
  const refreshDocuments=async()=>{try{setDocuments(await apis.documents.list())}catch{setAnnouncement('Vault could not be loaded')}}; const refreshPapers=async()=>{try{setPapers(await apis.papers.listPapers())}catch{setAnnouncement('Library could not be loaded')}}
  useEffect(()=>{void refreshPapers();void refreshDocuments()},[apis]); useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('paprv.theme',theme)}catch{return}},[theme])
  useEffect(()=>{const resize=()=>setLayout(currentLayout());window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[])
  useEffect(()=>{if(layout==='wide'||(layout==='intermediate'&&drawer==='explorer'))setDrawer(null)},[drawer,layout])
  useEffect(()=>{if(!drawer)return;const pane=drawer==='explorer'?explorerRef.current:inspectorRef.current;const modal=layout==='compact';const timer=modal?window.setTimeout(()=>{const controls=pane?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]');(controls?.[0]??pane)?.focus()},0):undefined;const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setDrawer(null);window.setTimeout(()=>drawerReturnRef.current?.focus(),0);return}if(!modal||event.key!=='Tab'||!pane)return;const controls=[...pane.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]')];if(controls.length===0){event.preventDefault();pane.focus();return}const first=controls[0],last=controls.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===pane)){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}};document.addEventListener('keydown',key);return()=>{if(timer!==undefined)window.clearTimeout(timer);document.removeEventListener('keydown',key)}},[drawer,layout])
  useEffect(()=>{if(!deleteDocumentId)return;window.setTimeout(()=>deleteDialogRef.current?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus(),0);const key=(event:KeyboardEvent)=>{if(!deleteDialogRef.current)return;if(event.key==='Escape'&&!deletePendingRef.current){event.preventDefault();setDeleteDocumentId(null);setDeleteError('');window.setTimeout(()=>deleteReturnRef.current?.focus(),0);return}if(event.key!=='Tab')return;const controls=[...deleteDialogRef.current.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];if(controls.length===0){event.preventDefault();deleteDialogRef.current.querySelector<HTMLElement>('[data-delete-busy]')?.focus();return}const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[deleteDocumentId])
  useEffect(()=>{if(!deletePending)return;const timer=window.setTimeout(()=>deleteDialogRef.current?.querySelector<HTMLElement>('[data-delete-busy]')?.focus(),0);return()=>window.clearTimeout(timer)},[deletePending])
  useEffect(()=>{if(!deleteError)return;window.setTimeout(()=>deleteDialogRef.current?.querySelector<HTMLElement>('[role="alert"]')?.focus(),0)},[deleteError])
  useEffect(()=>{if(!activeDocumentId){setProperties({documentId:'',papers:[],artifacts:[]});return}let active=true;const requestedId=activeDocumentId;void apis.documents.getProperties(requestedId).then(value=>{if(active&&value.documentId===requestedId)setProperties(value)},()=>{if(active)setAnnouncement('Properties could not be loaded')});return()=>{active=false}},[activeDocumentId,apis])
  const openDocument=async(id:string)=>{const intent=++openIntentRef.current;if(!(await docsRef.current?.openDocument(id)))return;setTabs(current=>current.some(t=>t.key===`document:${id}`)?current:[...current,{key:`document:${id}`,kind:'document',documentId:id}]);if(intent!==openIntentRef.current)return;setActiveKey(`document:${id}`)}
  const openStudy=async(id:string)=>{const intent=++openIntentRef.current;const sourceDocumentId=activeDocumentIdRef.current;const snapshot=sourceDocumentId?docsRef.current?.selectionSnapshot(sourceDocumentId)??null:null;setCapturedSelection(null);if(sourceDocumentId&&snapshot){const flushed=await docsRef.current?.flushDocument(sourceDocumentId);if(intent!==openIntentRef.current)return;if(!flushed){setActiveKey(`document:${sourceDocumentId}`);setAnnouncement('Study blocked: save this document before opening Study');window.setTimeout(()=>(document.querySelector<HTMLElement>('.editor-statusbar button:not(:disabled)')??document.querySelector<HTMLElement>('.markdown-editor'))?.focus(),0);return}const revision=docsRef.current?.revision(sourceDocumentId)??null;if(revision)setCapturedSelection({documentId:sourceDocumentId,revision,...snapshot})}try{const [paper,study,studyArtifacts]=await Promise.all([apis.papers.getPaper(id),apis.study.get(id),apis.study.listArtifacts(id)]);setPaperDetails(current=>({...current,[id]:paper}));setStudyViews(current=>({...current,[id]:study}));setArtifacts(current=>({...current,[id]:studyArtifacts}));setTabs(current=>current.some(t=>t.key===`study:${id}`)?current:[...current,{key:`study:${id}`,kind:'study',paperId:id}]);if(intent!==openIntentRef.current)return;setActiveKey(`study:${id}`)}catch{if(intent===openIntentRef.current)setAnnouncement('Study could not be opened')}}
  const newDocument=async()=>{if(docsRef.current?.isComposing())return;try{const created=await apis.documents.create({title:'Untitled',markdown:''});setDocuments(current=>[{id:created.id,title:created.title,revision:created.revision,updatedAt:created.updatedAt},...current]);await openDocument(created.id)}catch{setAnnouncement('Document could not be created')}}
  const closeTab=async(tab:OpenTab)=>{if(tab.kind==='document'&&!(await docsRef.current?.flushDocument(tab.documentId))){setActiveKey(tab.key);window.setTimeout(()=>document.querySelector<HTMLButtonElement>('.editor-statusbar button')?.focus(),0);return}const index=tabs.findIndex(t=>t.key===tab.key);const next=tabs.filter(t=>t.key!==tab.key);const replacement=next[Math.min(index,next.length-1)]??null;if(tab.kind==='document')docsRef.current?.closeDocument(tab.documentId);setTabs(next);if(activeKey===tab.key){setActiveKey(replacement?.key??null);window.setTimeout(()=>replacement&&document.querySelector<HTMLElement>(`[data-tab-key="${replacement.key}"]`)?.focus(),0)}}
  const deleteActive=async(id:string)=>{if(deletePendingRef.current||docsRef.current?.isComposing())return;deletePendingRef.current=true;setDeletePending(true);setDeleteError('');const flushed=await docsRef.current?.flushDocument(id);if(!flushed){deletePendingRef.current=false;setDeletePending(false);setDeleteDocumentId(null);await openDocument(id);setActiveKey(`document:${id}`);setAnnouncement('Deletion blocked: save this document before deleting it');window.setTimeout(()=>(document.querySelector<HTMLElement>('.editor-statusbar button')??document.querySelector<HTMLElement>('.markdown-editor'))?.focus(),0);return}try{await apis.documents.delete({documentId:id});const tab=tabs.find(t=>t.key===`document:${id}`);const tabIndex=tab?tabs.indexOf(tab):-1;const remaining=tabs.filter(t=>t.key!==`document:${id}`);const replacement=tab?remaining[Math.min(tabIndex,remaining.length-1)]??null:null;const compactInspector=layout==='compact'&&drawer==='inspector';if(tab)await closeTab(tab);setDocuments(current=>current.filter(d=>d.id!==id));setCapturedSelection(current=>current?.documentId===id?null:current);setDeleteDocumentId(null);if(compactInspector)setDrawer(null);setAnnouncement('Document deleted');window.setTimeout(()=>{if(replacement)document.querySelector<HTMLElement>(`[data-tab-key="${replacement.key}"]`)?.focus();else if(compactInspector)drawerReturnRef.current?.focus();else document.querySelector<HTMLButtonElement>('.new-document')?.focus()},0)}catch{setDeleteError('Document could not be deleted. Retrying is safe.')}finally{deletePendingRef.current=false;setDeletePending(false)}}
  useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if(modalOpen||compactDrawerOpen)return;if(!(event.metaKey||event.ctrlKey)||event.altKey)return;const key=event.key.toLowerCase();if(key==='1'){event.preventDefault();setActivity('library')}else if(key==='2'){event.preventDefault();setActivity('vault')}else if(key==='n'){event.preventDefault();void newDocument()}else if(key==='k'){event.preventDefault();quickRef.current?.focus()}else if(key==='s'&&activeDocumentId){event.preventDefault();void docsRef.current?.flushDocument(activeDocumentId)}else if(key==='t'&&event.shiftKey&&activePaper){event.preventDefault();generationReturnRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setGenerationOpen(true)}};document.addEventListener('keydown',shortcut);return()=>document.removeEventListener('keydown',shortcut)})
  useEffect(()=>{let appWindow:ReturnType<typeof getCurrentWindow>;try{appWindow=getCurrentWindow()}catch{return}let unlisten:(()=>void)|undefined;void appWindow.onCloseRequested(async event=>{event.preventDefault();if(closePendingRef.current)return;closePendingRef.current=true;const failedDocumentId=await docsRef.current?.flushAllDirtyDocuments()??null;if(failedDocumentId){closePendingRef.current=false;await openDocument(failedDocumentId);setAnnouncement('Close blocked: save every document before closing');window.setTimeout(()=>document.querySelector<HTMLElement>('.editor-statusbar button, .markdown-editor')?.focus(),0);return}try{await appWindow.destroy()}catch{closePendingRef.current=false;setAnnouncement('Close blocked: window could not be closed')}}).then(dispose=>{unlisten=dispose},()=>undefined);return()=>unlisten?.()},[])
  const filteredDocuments=documents.filter(d=>d.title.toLowerCase().includes(query.toLowerCase())); const filteredPapers=papers.filter(p=>`${p.title} ${p.authors.join(' ')} ${p.arxivId}`.toLowerCase().includes(query.toLowerCase()))
  const paperTabStopId=filteredPapers.some(paper=>paper.arxivId===paperRovingId)?paperRovingId:activeTab?.kind==='study'&&filteredPapers.some(paper=>paper.arxivId===activeTab.paperId)?activeTab.paperId:filteredPapers[0]?.arxivId
  const documentTabStopId=filteredDocuments.some(document=>document.id===documentRovingId)?documentRovingId:activeDocumentId&&filteredDocuments.some(document=>document.id===activeDocumentId)?activeDocumentId:filteredDocuments[0]?.id
  const modalOpen=generationOpen||importOpen||deleteDocumentId!==null
  const compactDrawerOpen=layout==='compact'&&drawer!==null
  const workspaceInert=modalOpen||compactDrawerOpen
  const tabTitle=(tab:OpenTab)=>tab.kind==='study'?(paperDetails[tab.paperId]?.title??tab.paperId):(documents.find(d=>d.id===tab.documentId)?.title??tab.documentId)
  const tabKey=(event:React.KeyboardEvent,tab:OpenTab)=>{const index=tabs.indexOf(tab);let target=index;if(event.key==='ArrowRight')target=Math.min(tabs.length-1,index+1);else if(event.key==='ArrowLeft')target=Math.max(0,index-1);else if(event.key==='Home')target=0;else if(event.key==='End')target=tabs.length-1;else return;event.preventDefault();const destination=tabs[target]!;if(destination.kind==='study')void openStudy(destination.paperId);else setActiveKey(destination.key);document.querySelector<HTMLElement>(`[data-tab-key="${destination.key}"]`)?.focus()}
  const explorerKey=(event:React.KeyboardEvent<HTMLButtonElement>)=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;const options=[...event.currentTarget.parentElement!.querySelectorAll<HTMLButtonElement>('[role="option"]')];const current=options.indexOf(event.currentTarget);const target=event.key==='Home'?0:event.key==='End'?options.length-1:event.key==='ArrowDown'?Math.min(options.length-1,current+1):Math.max(0,current-1);const destination=options[target];if(!destination)return;event.preventDefault();if(activity==='library')setPaperRovingId(destination.dataset.paperId??null);else setDocumentRovingId(destination.dataset.documentId??null);destination.focus()}
  const flushSource=async(id:string)=>{if(!(await docsRef.current?.flushDocument(id)))return null;return docsRef.current?.revision(id)??documents.find(d=>d.id===id)?.revision??null}
  const reloadArtifacts=()=>{if(activePaper)void apis.study.listArtifacts(activePaper.arxivId).then(value=>setArtifacts(current=>({...current,[activePaper.arxivId]:value})))}
  const refreshPropertiesAfterMutation=async(documentId:string)=>{const value=await apis.documents.getProperties(documentId);if(activeDocumentIdRef.current===documentId&&value.documentId===documentId)setProperties(value)}
  const linkPaper=async()=>{if(!activeDocumentId||!linkPaperId)return;const documentId=activeDocumentId;await apis.documents.linkPaper({documentId,paperId:linkPaperId});await refreshPropertiesAfterMutation(documentId);setAnnouncement('Paper link added')}
  const openDrawer=(target:'explorer'|'inspector',trigger:HTMLButtonElement)=>{drawerReturnRef.current=trigger;setDrawer(current=>current===target?null:target)}
  const closeImport=()=>{setImportOpen(false);window.setTimeout(()=>importReturnRef.current?.focus(),0)}
  const explorerHidden=layout==='compact'&&drawer!=='explorer'; const inspectorHidden=layout!=='wide'&&drawer!=='inspector'
  return <div className={`app-shell layout-${layout}`}><a className="skip-link" href="#workspace-main" inert={workspaceInert?true:undefined}>Skip to workspace</a><header className="app-topbar" inert={workspaceInert?true:undefined}><strong className="app-identity"><img src={paprvLogo} alt=""/>Paprv</strong><span className="workspace-label">{activity==='library'?'Library / Study':'Markdown Vault'}</span><label className="quick-search"><span className="visually-hidden">Quick search</span><input ref={quickRef} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Quick open…"/></label><span className="topbar-drag-region"/>{activity==='library'&&<button className="topbar-import" onClick={event=>{importReturnRef.current=event.currentTarget;setImportOpen(true)}}>Fetch from arXiv</button>}</header>
    <nav className="activity-ribbon" aria-label="Activities" inert={workspaceInert?true:undefined}><button aria-label="Library" title="Library · ⌘1" aria-current={activity==='library'?'page':undefined} aria-expanded={layout==='compact'?drawer==='explorer'&&activity==='library':undefined} onClick={event=>{setActivity('library');if(layout==='compact')openDrawer('explorer',event.currentTarget)}}><Icon name="library"/></button><button aria-label="Vault" title="Markdown Vault · ⌘2" aria-current={activity==='vault'?'page':undefined} aria-expanded={layout==='compact'?drawer==='explorer'&&activity==='vault':undefined} onClick={event=>{setActivity('vault');if(layout==='compact')openDrawer('explorer',event.currentTarget)}}><Icon name="file"/></button><button aria-label="Quick search" title="Quick open · ⌘K" onClick={()=>quickRef.current?.focus()}><Icon name="search"/></button><button aria-label="Properties and backlinks drawer" title="Properties and backlinks" aria-expanded={layout!=='wide'?drawer==='inspector':undefined} onClick={event=>openDrawer('inspector',event.currentTarget)}><Icon name="quote"/></button><button className="theme-toggle" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} title={`Switch to ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}><Icon name={theme==='dark'?'sun':'moon'}/></button></nav>
    <aside ref={explorerRef} className="library-pane" aria-label={activity==='library'?'Library Explorer':'Vault Explorer'} role={compactDrawerOpen&&drawer==='explorer'?'dialog':undefined} aria-modal={compactDrawerOpen&&drawer==='explorer'?true:undefined} aria-labelledby={compactDrawerOpen&&drawer==='explorer'?'explorer-drawer-title':undefined} tabIndex={compactDrawerOpen&&drawer==='explorer'?-1:undefined} style={{display:explorerHidden?'none':undefined}} hidden={explorerHidden} inert={modalOpen||(compactDrawerOpen&&drawer!=='explorer')?true:undefined}><div className="pane-heading"><h2 id="explorer-drawer-title">{activity==='library'?'LIBRARY':'VAULT'}</h2><span>{activity==='library'?papers.length:documents.length}</span></div>{activity==='vault'&&<button className="new-document" onClick={()=>{void newDocument()}}>New document</button>}<div className="paper-list" role="listbox" aria-label={activity==='library'?'Paper list':'Document list'}>{activity==='library'?filteredPapers.map((paper)=><button role="option" aria-selected={activeTab?.kind==='study'&&activeTab.paperId===paper.arxivId} tabIndex={paperTabStopId===paper.arxivId?0:-1} className="paper-list-item" data-paper-id={paper.arxivId} key={paper.arxivId} onKeyDown={explorerKey} onClick={()=>{setPaperRovingId(paper.arxivId);void openStudy(paper.arxivId)}}><strong>{paper.title}</strong><span>{paper.authors.join(', ')}</span><small>{paper.arxivId}</small></button>):filteredDocuments.map((document)=><button role="option" aria-selected={activeDocumentId===document.id} tabIndex={documentTabStopId===document.id?0:-1} className="paper-list-item" data-document-id={document.id} key={document.id} onKeyDown={explorerKey} onClick={()=>{setDocumentRovingId(document.id);void openDocument(document.id)}}><strong>{document.title}</strong><small>Revision {document.revision}</small></button>)}</div></aside>
    <main className="editor-pane vault-main" id="workspace-main" aria-label="Study and Markdown workspace" inert={workspaceInert?true:undefined}><div className="editor-modebar"><div className="document-tabs" role="tablist" aria-label="Open Study and documents">{tabs.map(tab=><div className="document-tab-item" key={tab.key}><button role="tab" aria-selected={tab.key===activeKey} tabIndex={tab.key===activeKey?0:-1} className="active-document-tab" data-tab-key={tab.key} onClick={()=>{if(tab.kind==='study')void openStudy(tab.paperId);else setActiveKey(tab.key)}} onKeyDown={e=>tabKey(e,tab)}><Icon name={tab.kind==='study'?'library':'file'} size={14}/><span>{tabTitle(tab)}</span></button><button type="button" className="tab-close" aria-label={`Close ${tabTitle(tab)}`} onClick={()=>{void closeTab(tab)}}>×</button></div>)}</div></div>
      {activeTab?.kind==='study'&&activePaper&&<section className="study-workspace"><header className="paper-properties"><h1>{activePaper.title}</h1><dl><div><dt>arXiv</dt><dd>{activePaper.arxivId}</dd></div><div><dt>Category</dt><dd>{activePaper.primaryCategory??'—'}</dd></div><div><dt>Published</dt><dd>{activePaper.publishedAt.slice(0,10)}</dd></div><div className="authors-property"><dt>Authors</dt><dd>{activePaper.authors.join(', ')}</dd></div></dl></header><div className="study-scroll"><section><h2>Abstract</h2><p>{activePaper.summary||'No stored abstract.'}</p></section><section className="study-generation"><h2>Study aids</h2><button className="primary-button" onClick={event=>{generationReturnRef.current=event.currentTarget;setGenerationOpen(true)}}>Generate study aid</button><p>Results remain a preview until you explicitly save an artifact.</p></section><section><h2>Saved artifacts</h2>{(artifacts[activePaper.arxivId]??[]).length===0?<p>No saved artifacts.</p>:<><label>Link artifact to document<select aria-label="Artifact link document" value={linkDocumentId} onChange={event=>setLinkDocumentId(event.target.value)}><option value="">Choose…</option>{documents.map(document=><option key={document.id} value={document.id}>{document.title}</option>)}</select></label>{(artifacts[activePaper.arxivId]??[]).map(item=><article className="saved-artifact" key={item.id}><strong>{item.level.replaceAll('_',' ')}</strong><span>{item.savedAt}</span><pre>{item.markdown}</pre><button type="button" aria-label="Link artifact to document" disabled={!linkDocumentId} onClick={()=>{void apis.documents.linkArtifact({documentId:linkDocumentId,artifactId:item.id}).then(()=>setAnnouncement('Artifact link added'),()=>setAnnouncement('Artifact could not be linked'))}}>Link to document</button></article>)}</>}</section></div></section>}
      {!activeTab&&<section className="workspace-empty" aria-label={activity==='library'?'No Study open':'No document open'}><Icon name={activity==='library'?'library':'file'}/><h1>{activity==='library'?'Open a paper Study':'Open a Vault document'}</h1><p>{activity==='library'?'Choose an imported paper from the Library to read its abstract and create study aids.':'Choose a document from the Vault or create a new Markdown document.'}</p></section>}
      <div className="document-host" hidden={activeTab?.kind!=='document'}><DocumentWorkspace ref={docsRef} activeDocumentId={activeDocumentId} api={apis.documents} onDocumentSaved={document=>{setDocuments(current=>current.map(item=>item.id===document.id?{id:document.id,title:document.title,revision:document.revision,updatedAt:document.updatedAt}:item));setCapturedSelection(current=>current?.documentId===document.id&&current.revision!==document.revision?null:current)}} onCopyCreated={document=>{setDocuments(current=>[{id:document.id,title:document.title,revision:document.revision,updatedAt:document.updatedAt},...current]);void openDocument(document.id)}}/></div>
    </main>
    <aside ref={inspectorRef} className="evidence-pane" aria-label="Properties and backlinks" role={compactDrawerOpen&&drawer==='inspector'?'dialog':undefined} aria-modal={compactDrawerOpen&&drawer==='inspector'?true:undefined} aria-labelledby={compactDrawerOpen&&drawer==='inspector'?'inspector-drawer-title':undefined} tabIndex={compactDrawerOpen&&drawer==='inspector'?-1:undefined} style={{display:inspectorHidden?'none':undefined}} hidden={inspectorHidden} inert={modalOpen||(compactDrawerOpen&&drawer!=='inspector')?true:undefined}><div className="pane-heading"><h2 id="inspector-drawer-title">PROPERTIES</h2></div>{activeDocumentId?<div className="panel-content"><p><strong>Explicit links only</strong></p><label>Link paper<select value={linkPaperId} onChange={e=>setLinkPaperId(e.target.value)}><option value="">Choose…</option>{papers.map(p=><option value={p.arxivId} key={p.arxivId}>{p.title}</option>)}</select></label><button disabled={!linkPaperId} onClick={()=>{void linkPaper()}}>Link paper</button><h3>Paper backlinks</h3>{properties.papers.length===0?<p>No paper links.</p>:properties.papers.map(p=><div className="property-link" key={p.arxivId}><span>{p.title}</span><button aria-label="Unlink paper" onClick={()=>{const documentId=properties.documentId;void apis.documents.unlinkPaper({documentId,paperId:p.arxivId}).then(()=>refreshPropertiesAfterMutation(documentId))}}>Unlink</button></div>)}<h3>Artifact backlinks</h3>{properties.artifacts.length===0?<p>No artifact links.</p>:properties.artifacts.map(a=><div className="property-link" key={a.artifactId}><span>{a.paperArxivId} · {a.artifactId}</span><button aria-label="Unlink artifact" onClick={()=>{const documentId=properties.documentId;void apis.documents.unlinkArtifact({documentId,artifactId:a.artifactId}).then(()=>refreshPropertiesAfterMutation(documentId))}}>Unlink</button></div>)}<button ref={deleteReturnRef} className="danger-button" onClick={()=>{if(activeDocumentId){setDeleteError('');setDeleteDocumentId(activeDocumentId)}}}>Delete document</button></div>:activePaper?<div className="panel-content"><p><strong>Stored edges only</strong></p><h3>Document backlinks</h3>{(studyViews[activePaper.arxivId]?.backlinks??[]).length===0?<p>No document links.</p>:(studyViews[activePaper.arxivId]?.backlinks??[]).map(backlink=><div className="property-link" key={backlink.documentId}><span>{backlink.title}</span></div>)}</div>:<p className="panel-content">Open a Study or document to inspect stored edges. Markdown text is never scanned for backlinks.</p>}</aside>
    {compactDrawerOpen&&<button type="button" className="drawer-scrim" data-drawer-scrim aria-label="Close drawer" onClick={()=>{setDrawer(null);window.setTimeout(()=>drawerReturnRef.current?.focus(),0)}}/>}{deleteDocumentId&&<div className="modal-layer"><button className="modal-scrim" aria-label="Cancel delete" disabled={deletePending} onClick={()=>{setDeleteDocumentId(null);setDeleteError('');window.setTimeout(()=>deleteReturnRef.current?.focus(),0)}}/><div ref={deleteDialogRef} className="transform-dialog delete-dialog" role="alertdialog" aria-modal="true" aria-busy={deletePending} aria-labelledby="delete-title" aria-describedby="delete-description"><h2 id="delete-title">Delete document permanently?</h2><p id="delete-description">This cannot be undone.</p><p role="status" aria-live="polite" tabIndex={-1} data-delete-busy>{deletePending?'Deleting document…':''}</p>{deleteError&&<p className="transform-error" role="alert" tabIndex={-1}>{deleteError}</p>}<div className="dialog-actions"><button disabled={deletePending} onClick={()=>{setDeleteDocumentId(null);setDeleteError('');window.setTimeout(()=>deleteReturnRef.current?.focus(),0)}}>Cancel</button><button className="danger-button" disabled={deletePending} onClick={()=>{void deleteActive(deleteDocumentId)}}>{deletePending?'Deleting…':deleteError?'Retry delete':'Delete permanently'}</button></div></div></div>}
    <span className="visually-hidden" role="status" aria-live="polite">{announcement}</span>{generationOpen&&activePaper&&<StudyGenerationDialog paperId={activePaper.arxivId} documents={documents} selection={capturedSelection} generation={apis.generation} study={apis.study} flushDocument={flushSource} onSaved={reloadArtifacts} onClose={()=>{setGenerationOpen(false);window.setTimeout(()=>generationReturnRef.current?.focus(),0)}}/>}<ImportPaperDialog open={importOpen} papersApi={apis.papers} existingIds={new Set(papers.map(p=>p.arxivId))} onClose={closeImport} onFetched={paper=>{setPapers(current=>[paper,...current.filter(p=>p.arxivId!==paper.arxivId)])}} onOpenPaper={async paper=>{setPaperDetails(current=>({...current,[paper.arxivId]:paper}));await openStudy(paper.arxivId);closeImport()}}/>
  </div>
}
export function App({apis=defaults}:{apis?:WorkspaceApis}) { useEffect(()=>{document.title='Paprv'},[]); return <StartupBoundary><Workspace apis={apis}/></StartupBoundary> }
